### ISSUE TITLE
OnGestureListener always receiving the same Node

### ISSUE THREAD

**Issue by dzivko1** [SceneView/sceneview-android#400] opened 2024-01-24 13:06 UTC
I'm trying to detect when a certain model is tapped in a 3D model viewer. I'm using `OnGestureListener.onSingleTapUp` to detect taps. The taps are detected, but the `Node` I receive in the callback is always the first node that is added to `childNodes`, no matter where I tap on the screen and no matter the camera orientation.

Here is a reproducible example of what I mean.

```
@Composable
fun SceneViewTest() {
  val engine = rememberEngine()
  val modelLoader = rememberModelLoader(engine)
  var c by remember { mutableIntStateOf(0) }
  Scene(
    modifier = Modifier.fillMaxSize(),
    engine = engine,
    modelLoader = modelLoader,
    childNodes = rememberNodes {
      add(ModelNode(modelLoader.createModelInstance("sofa.glb")).apply {
        position = Position(z = -4.0f)
        scale = Scale(0.25f)
      })
      add(ModelNode(modelLoader.createModelInstance("bulb.glb")).apply {
        position = Position(x = 0.5f, z = -4.0f)
        scale = Scale(0.01f)
      })
    },
    onGestureListener = rememberOnGestureListener(
      onSingleTapUp = { _, node ->
        // node is always the first added node, in this case "sofa.glb"
        node?.scale = Scale(if (c++ % 2 == 0) 0.5f else 0.25f)
      }
    )
  )
}
```

I would expect the received node to be the one that is tapped. Am I missing something? How can I know which node was tapped on the screen?

**Comment by KvRae** [comment] 2024-03-05 09:35
Do you happen to have any updates on this?

**Comment by dzivko1** [comment] 2024-03-05 14:21
Sadly, no. I put this on pause since I couldn't find a solution.

**Comment by KvRae** [comment] 2024-03-05 16:46
I spoke with @grassydragon on Discord recently  and he said that he will try to reproduce it

**Comment by grassydragon** [comment] 2024-03-08 12:28
It looks like the bounding box of a `Node` isn't updated inside the collision system with respect to its position, rotation and scale. I think I'll need some time to work on this issue.

**Comment by ThomasGorisse** [comment] 2024-05-29 17:17
Fixed in [v2.2.0](https://github.com/SceneView/sceneview-android/releases/tag/v2.2.0)

**Closed by ThomasGorisse** 2024-05-29 17:17 UTC

**Comment by KvRae** [comment] 2024-05-30 10:54
I've tested it out, the good thing is it works for some nodes like `CylinderNode() `and `CubeNode() `but it doesnt work with the `ShapeNode()` it returns always the same cords for the parent,

**Comment by KvRae** [comment] 2024-05-30 10:55
@ThomasGorisse I can provide you some screenshots about the logs if you want
